spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rbm?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    hikari:
      pool-name: springHikariCP
      connection-timeout: 5000
      minimum-idle: 5
      idle-timeout: 180000
      max-lifetime: 1800000
      maximum-pool-size: 10

  data:
    solr:
      host: http://admin:xkw.com1QAZ@rbm.xkw.com/solr